language: python
python:
- "3.6"

sudo: required

install:
- "git clone https://github.com/0x00-0x00/shemutils.git"
- "cd shemutils/; python setup.py install; cd ~/build/0x00-0x00/crypt"
- "python setup.py install"
- "pip -r requirements.txt"
- "cd travis_test/"
- "echo '[*] Ready to begin test phase.'"


script:
- "crypt -h"

- "crypt --encrypt --file test.file -k"

- "crypt --decrypt --file test.file.enc -k"
- "rm test.file.enc"


- "crypt --encrypt --file test.file -k -u"

- "crypt --decrypt --file test.file.enc -k -u"

