language: python
python:
- "3.6"

sudo: required

install:
- "sudo ./bootstrap.sh"
- "git clone https://github.com/0x00-0x00/shemutils.git"
- "cd shemutils/; python setup.py install; cd ../crypt"
- "python setup.py install"

script:
- "crypt -h"